import { Routes } from '@angular/router';
import { Sjm1VeinMaintenanceComponent } from './sjm1-vein-maintenance.component';
import { SjmCrrtVeinMaintenanceComponent } from './sjm-crrt-vein-maintenance.component';
import { YdwzlTemperatureComponent } from './ydwzl-temperature.component';
import { ToleranceScoreComponent } from './tolerance-score.component';
import { CommitSuicideScoreComponent } from './commit-suicide-score.component';
import { IadScoreComponent } from './iad-score.component';
import { BaetheiScoreComponent } from './baethei-score.component';
import { PatientFallDangerComponent } from './patient-fall-danger.component';
import { HealthEducationComponent } from './health-education.component';
import { WpgmFormComponent } from './wpgm-form.component';
import { EcmoRecordComponent } from './ecmo-record.component';
import { TransfusionRecordComponent } from './transfusion-record.component';
import { PiccoRecordComponent } from './picco-record.component';
import { IabpRecordComponent } from './iabp-record.component';
import { TemperatureRecordComponent } from './temperature-record.component';
import { BradenFormComponent } from './braden-form.component';
import { CrrtRecordComponent } from './crrt-record.component';
import { CrrtOrderFormComponent } from './crrt-order-form.component';
import { HljldFormComponent } from './hljld-form.component';
import { HljldFormPdfComponent } from './hljld-form-pdf.component';
import { HandoverReportComponent } from './handover-report.component';
import { BloodSugarComponent } from './blood-sugar.component';
import { UnplannedExtubationComponent } from './unplanned-extubation.component';
import { PrintCenterComponent } from './print-center.component';

export const routes: Routes = [
  { path: 'sjm1', component: Sjm1VeinMaintenanceComponent },
  { path: 'sjmCrrt', component: SjmCrrtVeinMaintenanceComponent },
  { path: 'ydwzlForm', component: YdwzlTemperatureComponent },
  { path: 'toleranceForm', component: ToleranceScoreComponent },
  { path: 'commitSuicideForm', component: CommitSuicideScoreComponent },
  { path: 'IADForm', component: IadScoreComponent },
  { path: 'baetheiForm', component: BaetheiScoreComponent },
  { path: 'patientFallDangerForm', component: PatientFallDangerComponent },
  { path: 'jkjyForm', component: HealthEducationComponent },
  { path: 'wpgmForm', component: WpgmFormComponent },
  { path: 'ecmoForm', component: EcmoRecordComponent },
  { path: 'bradenForm', component: BradenFormComponent },
  { path: 'transfusionForm', component: TransfusionRecordComponent },
  { path: 'piccoForm', component: PiccoRecordComponent },
  { path: 'iabpForm', component: IabpRecordComponent },
  { path: 'crrtForm', component: CrrtRecordComponent },
  { path: 'crrtOrderForm', component: CrrtOrderFormComponent },
  { path: 'hljldForm', component: HljldFormComponent },
  { path: 'hljldFormPDF', component: HljldFormPdfComponent },
  { path: 'handoverReport', component: HandoverReportComponent },
  { path: 'bloodSugar', component: BloodSugarComponent },
  { path: 'temperatureRecord', component: TemperatureRecordComponent },
  { path: 'unPlannedCGZYYForm', component: UnplannedExtubationComponent },
  { path: 'printCenter', component: PrintCenterComponent },
  { path: '', redirectTo: 'sjm1', pathMatch: 'full' },
];
